import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SocketProvides } from "@/provider/SocketProvides";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SocketProvides>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SocketProvides>
    </ClerkProvider>
  );
}
